[custom]
;ruleset=策略组+规则，一个策略组可以对应多个规则
ruleset=🎓 学术,clash-classic:https://raw.githubusercontent.com/Shayne-iaMi/clash-rule/refs/heads/main/academic.yaml
;ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
;ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
;ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list
;ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list
;ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list
ruleset=🛑 广告拦截,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ZhihuAds/ZhihuAds.yaml
ruleset=🛑 广告拦截,clash-domain:https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Clash.yaml

ruleset=🎯 国内流量,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/SteamCN/SteamCN.yaml
ruleset=🎯 国内流量,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.yaml
;ruleset=🎯 国内流量,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 国内流量,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🎯 国内流量,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 国内流量,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 国内流量,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 国内流量,[]GEOIP,CN
ruleset=🎯 全球直连,clash-domain:https://ghproxy.085404.xyz/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt
ruleset=🎯 全球直连,clash-classic:https://raw.githubusercontent.com/sun2ot/ClashRules/refs/heads/main/RuleSet/cnip.yaml

ruleset=🧚 AI,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.yaml
ruleset=🧚 AI,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Claude/Claude.yaml
ruleset=🧚 AI,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.yaml
ruleset=🧚 AI,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Copilot/Copilot.yaml
ruleset=🛸 IP归属地伪装,clash-classic:https://raw.githubusercontent.com/lwd-temp/anti-ip-attribution/main/generated/rule-provider.yaml
ruleset=👨‍💻 GitHub,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.yaml
ruleset=Ⓜ️ 微软云盘,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive.yaml
ruleset=Ⓜ️ 微软服务,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml

ruleset=🚀 节点选择,clash-classic:https://ghproxy.085404.xyz/https://raw.githubusercontent.com/sun2ot/ClashRules/main/RuleSet/CustomizeProxy.yaml
ruleset=🚀 节点选择,clash-domain:https://ghproxy.085404.xyz/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt
ruleset=🚀 节点选择,clash-classic:https://ghproxy.085404.xyz/https://raw.githubusercontent.com/sun2ot/GitHubIP2COS/master/tmp/ghip.yaml
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🚀 节点选择,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PikPak/PikPak.yaml

ruleset=🐟 漏网之鱼,[]FINAL

;策略组节点选择, 类型为select, 内含direct和所有节点. 给定测速链接,每隔50000秒测速一次,3秒后判定为timeout
custom_proxy_group=🚀 节点选择`select`[]DIRECT`.*`http://www.gstatic.com/generate_204`100000,3
custom_proxy_group=🎓 学术`select`[]DIRECT`[]🚀 节点选择`
custom_proxy_group=🧚 AI`select`.*`
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]🎯 国内流量`[]🚀 节点选择
custom_proxy_group=🛸 IP归属地伪装`select`[]🎯 国内流量`(CN|电信|联通|移动)` 
custom_proxy_group=👨‍💻 GitHub`select`[]🚀 节点选择`[]🎯 国内流量` 
custom_proxy_group=Ⓜ️ 微软云盘`select`[]🎯 国内流量`[]🚀 节点选择` 
custom_proxy_group=Ⓜ️ 微软服务`select`[]🎯 国内流量`[]🚀 节点选择` 
custom_proxy_group=🎯 国内流量`select`[]DIRECT`[]🚀 节点选择` 
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]🎯 国内流量` 

enable_rule_generator=true
overwrite_original_rules=true
